#!/usr/bin/env python
# -*- coding: utf-8 -*-

import binascii
import copy
from tinydexparser import TinyParser
import math
import os.path
import scurve
import string
import sys

from PIL import Image, ImageDraw
from scurve import progress, utils, draw

# ———————————————————————————————————————————

class _Color:
    def __init__(self, data, **kwargs):
        self.data = data
        for key, value in kwargs.items():
            setattr(self, key, value)
        s = list(set(data))
        s.sort()
        self.symbol_map = {v : i for (i, v) in enumerate(s)}

    def __len__(self):
        return len(self.data)

    def point(self, x):
        if hasattr(self, 'override'):
            return self.getPoint(x)
        attrs = vars(self)
        if 'data' in attrs:
            attrs.pop('data', None)
        if 'symbol_map' in attrs:
            attrs.pop('symbol_map', None)
        for key in attrs:
            value = getattr(self, key, None)
            if value is not None and len(value) >= 2 and value[0] <= x <= value[1]:
                if key.startswith('proto_params_'):
                    return self.droidcolors_proto_params(x)
                elif key.startswith('class_ifs_'):
                    return self.droidcolors_class_ifs(x)
                elif key.startswith('encoded_values_'):
                    return self.droidcolors_encoded_vals(x)
                elif key.startswith('annotation_'):
                    return self.droidcolors_annotations(x)
                elif key.startswith('class_data_') or key.startswith('strings_') or key == 'block':
                    return value[2]
                else:
                    method_name = 'droidcolors_' + key
                    return getattr(self, method_name)(x)
        return self.getPoint(x)

    def return_class(self, x):
        c = ord(self.data[x])
        if c == 0:
            return [0, 0, 0]
        elif c == 255:
            return [255, 255, 255]
        elif chr(c) in string.printable:
            return [55, 126, 184]
        return [228, 26, 28]

    def droidcolors_annotations(self, x):
        return [155, 0, 175]

    def droidcolors_class_defs(self, x):
        return [237, 248, 251]

    def droidcolors_class_ifs(self, x):
        return [0, 150, 255]

    def droidcolors_data(self, x):
        return [100, 100, 100]

    def droidcolors_dexmap(self, x):
        return [0, 0, 255]

    def droidcolors_encoded_vals(self, x):
        return [155, 150, 0]

    def droidcolors_field_ids(self, x):
        return [153, 216, 201]

    def droidcolors_header(self, x):
        return [255, 0, 0]

    def droidcolors_links(self, x):
        return [255, 255, 0]

    def droidcolors_method_ids(self, x):
        return [204, 236, 230]

    def droidcolors_proto_ids(self, x):
        return [102, 194, 164]

    def droidcolors_proto_params(self, x):
        return [0, 100, 255]

    def droidcolors_string_ids(self, x):
        return [0, 109, 44]

    def droidcolors_type_ids(self, x):
        return [44, 162, 95]

    def return_entropy(self, x):
        e = utils.entropy(self.data, 32, x, len(self.symbol_map))
        # http://www.wolframalpha.com/input/?i=plot+%284%28x-0.5%29-4%28x-0.5%29**2%29**4+from+0.5+to+1
        def curve(v):
            f = (4*v - 4*v**2)**4
            f = max(f, 0)
            return f
        r = curve(e-0.5) if e > 0.5 else 0
        b = e**2
        return [
            int(255*r),
            0,
            int(255*b)
        ]

    def return_gradient(self, x):
        pass

    def return_hilbert(self, x):
        pass

# ———————————————————————————————————————————

class ColorClass(_Color):
    def getPoint(self, x):
        c = ord(self.data[x])
        if c == 0:
            return [0, 0, 0]
        elif c == 255:
            return [255, 255, 255]
        elif chr(c) in string.printable:
            return [55, 126, 184]
        return [228, 26, 28]

# ———————————————————————————————————————————

class ColorDroidColors(_Color):
    def getPoint(self, x):
        return [0, 0, 0]

# ———————————————————————————————————————————

class ColorEntropy(_Color):
    def getPoint(self, x):
        e = utils.entropy(self.data, 32, x, len(self.symbol_map))
        # http://www.wolframalpha.com/input/?i=plot+%284%28x-0.5%29-4%28x-0.5%29**2%29**4+from+0.5+to+1
        def curve(v):
            f = (4*v - 4*v**2)**4
            f = max(f, 0)
            return f
        r = curve(e-0.5) if e > 0.5 else 0
        b = e**2
        return [
            int(255*r),
            0,
            int(255*b)
        ]

# ———————————————————————————————————————————

class ColorGradient(_Color):
    def getPoint(self, x):
        c = ord(self.data[x])/255.0
        return [
            int(255*c),
            int(255*c),
            int(255*c)
        ]

# ———————————————————————————————————————————

class ColorHilbert(_Color):
    def __init__(self, data, **kwargs):
        _Color.__init__(self, data, **kwargs)
        self.csource = scurve.fromSize("hilbert", 3, 256**3)
        self.step = len(self.csource)/float(len(self.symbol_map))

    def getPoint(self, x):
        c = self.symbol_map[self.data[x]]
        return self.csource.point(int(c*self.step))

# ———————————————————————————————————————————

def drawmap_unrolled(map, size, csource, name, prog):
    prog.set_target((size**2)*4)
    map = scurve.fromSize(map, 2, size**2)
    c = Image.new("RGB", (size, size*4))
    cd = ImageDraw.Draw(c)
    step = len(csource)/float(len(map)*4)

    sofar = 0
    for quad in range(4):
        for i, p in enumerate(map):
            off = (i + (quad * size**2))
            color = csource.point(
                        int(off * step)
                    )
            x, y = tuple(p)
            cd.point(
                (x, y + (size * quad)),
                fill=tuple(color)
            )
            if not sofar%100:
                prog.tick(sofar)
            sofar += 1
    c.save(name)

# ———————————————————————————————————————————

def drawmap_square(map, size, csource, name, prog):
    prog.set_target((size**2))
    map = scurve.fromSize(map, 2, size**2)
    c = Image.new("RGB", map.dimensions())
    cd = ImageDraw.Draw(c)
    step = len(csource)/float(len(map))
    for i, p in enumerate(map):
        color = csource.point(int(i*step))
        cd.point(tuple(p), fill=tuple(color))
        if not i%100:
            prog.tick(i)
    c.save(name)

# ———————————————————————————————————————————

def main():
    from optparse import OptionParser, OptionGroup
    parser = OptionParser(
                usage = "%prog [options] infile [output]",
                version="%prog 0.1",
            )
    parser.add_option(
        "-b", "--block", action="store",
        dest="block", default=None,
        help="Mark a block of data with a specified color. Format: hexstartaddr:hexendaddr[:hexcolor]"
    )
    parser.add_option(
        "-c", "--color", action="store",
        type="choice", dest="color", default="droidcolors",
        choices=["class", "droidcolors", "hilbert", "entropy", "gradient"],
        help="Color map."
    )
    parser.add_option(
        "-m", "--map", action="store",
        type="choice", dest="map", default="hilbert",
        choices=sorted(scurve.curveMap.keys()),
        help="Pixel layout map. Can be any supported curve."
    )
    parser.add_option(
        "-n", "--namesuffix", action="store",
        type="str", dest="suffix", default="",
        help="Suffix for generated file names. Ignored if destination is specified."
    )
    parser.add_option(
        "-p", "--progress", action="store_true", default=False,
        dest="progress",
        help="Don't show progress bar - print the destination file name."
    )
    parser.add_option(
        "-s", "--size", action="store",
        type="int", dest="size", default=256,
        help="Image width in pixels."
    )
    parser.add_option(
        "-t", "--type", type="choice",
        dest="type", default="unrolled",
        choices=["unrolled", "square"],
        help="Image aspect ratio - square (1x1) or unrolled (1x4)"
    )
    parser.add_option(
        "-q", "--quiet", action="store_true",
        dest="quiet", default=False
    )
    options, args = parser.parse_args()
    if len(args) not in [1, 2]:
        parser.error("Please specify input and output file.")

    d = file(args[0]).read()
    if len(args) == 2:
        dst = args[1]
    else:
        base = os.path.basename(args[0])
        if "." in base:
            base, _ = base.rsplit(".", 1)
        dst = base + options.suffix + ".png"

    if os.path.exists(dst) and len(args) < 2:
        print >> sys.stderr, "Refusing to over-write '%s'. Specify explicitly if you really want to do this."%dst
        sys.exit(1)

    block = None
    if options.block:
        parts = options.block.split(":")
        if len(parts) not in [2, 3]:
            raise ValueError("Invalid block specification.")
        s, e = int(parts[0], 16), int(parts[1], 16)
        if len(parts) == 3:
            c = draw.parseColor(parts[2])
        else:
            c = [255, 0, 0]
        block = (s, e, c)

    if options.color == "class":
        csource = ColorClass(d, block=block, override=True)
    elif options.color == "hilbert":
        csource = ColorHilbert(d, block=block, override=True)
    elif options.color == "gradient":
        csource = ColorGradient(d, block=block, override=True)
    elif options.color == "entropy":
        csource = ColorEntropy(d, block=block, override=True)
    else:
        dex_handle = TinyParser(args[0])
        kwarg_dict = dex_handle.get_offsets()

        csource = ColorDroidColors(
            d,
            **kwarg_dict
        )

    if options.progress:
        print dst

    if options.quiet or options.progress:
        prog = progress.Dummy()
    else:
        prog = progress.Progress(None)

    if options.type == "unrolled":
        drawmap_unrolled(options.map, options.size, csource, dst, prog)
    elif options.type == "square":
        drawmap_square(options.map, options.size, csource, dst, prog)
    prog.clear()

main()
